* Iteration 00 - Project Setup
Even though we want to focus on working with what "the platform" (i.e the browser)
already provides for us, there are still some external dependencies we will use
to make our lives easier. npm is best in managing those.
So as a prerequisite, we need [[https://docs.npmjs.com/downloading-and-installing-node-js-and-npm][node + npm installed]].

Next, run =npm init= to initialize project. Defaults should be fine.

Now cretae a "hello world" index.html file in the root of the project, so we have somehing to display.
Something like this is just fine:

#+begin_example html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PWA Training</title>
  </head>
  <body>
      <h1>Hello world</h1>
  </body>
</html>
#+end_example

For local development we want to make sure that our browser is refreshed whenever
we did code changes, so let's setup [[https://www.browsersync.io][browser-sync]] to help us here:

=npm install browser-sync --save-dev=

This added the package in the dev-dependencies section, but nothing more.
In order to become useful, add the following line under scripts in our package.json.

="start": "browser-sync start server --files \"**/*.js\" --files \"**/*.html\" --files \"**/*.css\""=

The above line will start a server (port 3000 by default) and watch all js, html and css files for changes.

Test it by running npm run start.
